/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
   {
      type: 'category',
      label: 'Learn',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'learn',
        },
      ],
    },
   {
      type: 'category',
      label: 'Build',
      link: {
        type: 'generated-index',
      },
      items: [
       {
          type: 'category',
          label: 'Writing plugins',
          link: {
            type: 'generated-index',
          },
          items: ['build/plugins'],
        },
       {
          type: 'category',
          label: 'Deployment',
          link: {
            type: 'generated-index',
          },
          items: ['dummy'],
        },
       {
          type: 'category',
          label: 'Contributing',
          link: {
            type: 'generated-index',
          },
          items: ['dummy'],
        },
     {
        type: 'category',
        label: 'Reference',
        link: {
          type: 'generated-index',
        },
        items: [
          { type: 'link', label: 'API', href: '/api' },
          'sdk-ts', 'sdk-go', 'glossary'],
      },
     {
        type: 'category',
        label: 'Under the hood',
        link: {
          type: 'generated-index',
        },
        items: [
          {
            type: 'autogenerated',
            dirName: 'arch',
          },
        ],
      },
        ],
      },
     {
        type: 'category',
        label: 'Create',
        link: {
          type: 'generated-index',
        },
        items: ['dummy'],
      },
  ],
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

};

module.exports = sidebars;
