name: Test build

on:
  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read

jobs:
  test-deploy:
    name: Test build
    runs-on: self-hosted  #ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci
      - name: Test build website
        run: npm run build
